language: objective-c

before_install: 
- gem install cocoapods
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build test -workspace JSQDataSourcesKit.xcworkspace -scheme Example -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO

# Uncomment when travis-ci supports Xcode 6.3 and Swift 1.2
#
# - xctool clean build test -project JSQDataSourcesKit/JSQDataSourcesKit.xcodeproj -scheme JSQDataSourcesKit -sdk iphonesimulator8.3 ONLY_ACTIVE_ARCH=NO
