osx_image: xcode7.1

language: objective-c

env:
   global:
   - LANG=en_US.UTF-8

   matrix:
   - DESTINATION="OS=8.1,name=iPhone 4s" SDK=iphonesimulator9.1
   - DESTINATION="OS=8.2,name=iPhone 5" SDK=iphonesimulator9.1
   - DESTINATION="OS=8.3,name=iPhone 5s" SDK=iphonesimulator9.1
   - DESTINATION="OS=8.4,name=iPhone 6" SDK=iphonesimulator9.1
   - DESTINATION="OS=9.1,name=iPhone 6 Plus" SDK=iphonesimulator9.1
   - DESTINATION="OS=9.1,name=iPhone 6s" SDK=iphonesimulator9.1
   - DESTINATION="OS=9.1,name=iPhone 6s Plus" SDK=iphonesimulator9.1

   - DESTINATION="OS=8.1,name=iPad 2" SDK=iphonesimulator9.1
   - DESTINATION="OS=8.4,name=iPad Retina" SDK=iphonesimulator9.1
   - DESTINATION="OS=9.1,name=iPad Air" SDK=iphonesimulator9.1


# before_install:
# - brew update
# - brew outdated xctool || brew upgrade xctool

script:
- pod spec lint
- pod lib lint

- xctool clean build test -workspace JSQDataSourcesKit.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

- xctool clean build test -workspace JSQDataSourcesKit.xcworkspace -scheme JSQDataSourcesKit -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO

- xcodebuild test -project JSQDataSourcesKit/JSQDataSourcesKit.xcodeproj -scheme JSQDataSourcesKit -sdk iphonesimulator

after_success:
- bash <(curl -s https://codecov.io/bash)
